config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'up', to: 'rails/health#show', as: :rails_health_check

  scope module: :web do
    root 'bulletins#index'

    resources :bulletins, only: %i[new create edit update index show] do
      patch :to_moderate, on: :member
      patch :archive, on: :member
    end

    post '/auth/:provider', to: 'auth#request', as: :auth_request
    get '/auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete '/auth', to: 'auth#destroy', as: :destroy_user_session

    namespace :admin do
      root 'home#index'

      resources :bulletins, only: %i[index] do
        patch :archive, on: :member
        patch :publish, on: :member
        patch :reject, on: :member
      end

      resources :categories, only: %i[create destroy edit index new update]
    end

    resource :profile, only: %i[show]
  end
end

app/views/layouts/shared/_flash.html.slim
- if flash.any?
  .container.my-2
    - flash.each do |_type, msg|
      .alert.alert-info
        = msg

app/views/layouts/shared/_nav.html.slim
.container.mb-2
  .py-2.border-bottom
    .d-flex.flex-wrap.align-items-center.py-2
      .navbar.navbar-expand-md.navbar-light
        div
          = link_to root_path, class: 'navbar-brand me-md-4' do
            = image_tag asset_path('logo.png'), width: 30, alt: t('.hexlet_logo')
        div
          #navbarToggler.collapse.navbar-collapse
            ul.nav.nav-pills.flex-grow-1.navbar-nav
              - if user_signed_in?
                li.nav-link.disabled
                  = current_user.email
                li.nav-item
                  = link_to destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: t('logout_confirmation') }, class: 'nav-link link-dark' do
                    = t('logout')
                li.nav-item
                  = link_to profile_path, class: 'nav-link link-dark' do
                    = t('user_bulletin')
                    li.nav-item
                li.nav-item
                  = link_to new_bulletin_path, class: 'nav-link link-dark' do
                    = t('create_bulletin')
                    li.nav-item
                - if current_user.admin?
                  = link_to admin_root_url, class: 'nav-link link-dark' do
                    = t('admin')
                    li.nav-item
              - else
                li.nav-item
                  = button_to t('login'), auth_request_path('github'), data: { turbo: false }, method: :post, class: 'nav-link link-dark'