config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'up', to: 'rails/health#show', as: :rails_health_check

  scope module: :web do
    root 'bulletins#index'

    resources :bulletins, only: %i[new create edit update index show] do
      patch :to_moderate, on: :member
      patch :archive, on: :member
    end

    post '/auth/:provider', to: 'auth#request', as: :auth_request
    get '/auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete '/auth', to: 'auth#destroy', as: :destroy_user_session

    namespace :admin do
      root 'home#index'

      resources :bulletins, only: %i[index] do
        patch :archive, on: :member
        patch :publish, on: :member
        patch :reject, on: :member
      end

      resources :categories, only: %i[create destroy edit index new update]
    end

    resource :profile, only: %i[show]
  end
end

app/models/bulletin.rb
# frozen_string_literal: true

class Bulletin < ApplicationRecord
  include AASM

  belongs_to :category
  belongs_to :user, class_name: 'User'

  has_one_attached :image

  validates :title, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 1000 }
  validates :image, presence: true,
                    content_type: %i[png jpg jpeg],
                    size: { less_than: 5.megabytes }

  aasm column: 'state' do
    state :draft, initial: true
    state :under_moderation, :published, :rejected, :archived

    event :to_moderate do
      transitions from: :draft, to: :under_moderation
    end

    event :publish do
      transitions from: :under_moderation, to: :published
    end

    event :reject do
      transitions from: :under_moderation, to: :rejected
    end

    event :archive do
      transitions from: %i[draft under_moderation published rejected], to: :archived
    end
  end

  def self.ransackable_attributes(_auth_object = nil)
    %w[title category_id state]
  end
end

app/controllers/web/admin/bulletins_controller.rb
# frozen_string_literal: true

module Web
  module Admin
    class BulletinsController < ApplicationController
      def index
        @search = Bulletin.order('created_at DESC').ransack(params[:q])
        @bulletins = @search.result.page(params[:page]).per(10)
      end

      def archive
        @bulletin = Bulletin.find(params[:id])
        @bulletin.archive! if @bulletin.may_archive?
        redirect_back(fallback_location: admin_root_path, notice: t('.archive_success'))
      end

      def publish
        @bulletin = Bulletin.find(params[:id])
        @bulletin.publish! if @bulletin.may_publish?
        redirect_to admin_root_url, notice: t('.publish_success')
      end

      def reject
        @bulletin = Bulletin.find(params[:id])
        @bulletin.reject! if @bulletin.may_reject?
        redirect_to admin_root_url, notice: t('.reject_success')
      end
    end
  end
end

app/controllers/web/bulletins_controller.rb
# frozen_string_literal: true

module Web
  class BulletinsController < ApplicationController
    before_action :user_authorize, only: %i[new create]

    def index
      @search = Bulletin.where(state: 'published').order('created_at DESC').ransack(params[:q])
      @bulletins = @search.result.page(params[:page]).per(12)
    end

    def show
      @bulletin = Bulletin.find(params[:id])
      authorize @bulletin
    end

    def new
      @bulletin = current_user.bulletins.build
    end

    def edit
      @bulletin = Bulletin.find(params[:id])
      authorize @bulletin
    end

    def create
      @bulletin = current_user.bulletins.new(bulletin_params)
      if @bulletin.save
        redirect_to bulletin_url(@bulletin), notice: t('.create_success')
      else
        render :new, status: :unprocessable_entity
      end
    end

    def to_moderate
      @bulletin = Bulletin.find(params[:id])
      authorize @bulletin
      @bulletin.to_moderate! if @bulletin.may_to_moderate?
      redirect_to profile_path, notice: t('.to_moderate_success')
    end

    def update
      @bulletin = Bulletin.find(params[:id])
      authorize @bulletin
      if @bulletin.update(bulletin_params)
        redirect_to bulletin_url(@bulletin), notice: t('.update_success')
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def archive
      @bulletin = Bulletin.find(params[:id])
      authorize @bulletin
      @bulletin.archive! if @bulletin.may_archive?
      redirect_to profile_path, notice: t('.archive_success')
    end

    private

    def bulletin_params
      params.require(:bulletin).permit(:title, :description, :category_id, :image)
    end
  end
end

app/views/web/bulletins/_bulletin.html.slim
.col-3.pt2 id="#{dom_id bulletin}"
  .card.shadow-sm
    - if bulletin.image_attachment
      = image_tag bulletin.image, class: 'card-img-top x-object-fit-cover', height: 200
    .card-body
      h4
        =< link_to bulletin.title, bulletin, style: 'color: black; text-decoration: none;'
      .text-left.small.text-muted.mt-auto
        span.me-2
          = time_ago_in_words(bulletin.created_at)
  p

app/views/web/bulletins/_form.html.slim
= simple_form_for(bulletin) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors.full_messages.to_sentence if f.object.errors.any?

  .form-inputs
    = f.input :title, label: t('title')
    = f.input :description, label: t('description')
    = f.association :category, label: t('category'), required: true
    .form-group.file.required.bulletin_image
    - if bulletin.image.attached? && !bulletin.image.attachment.new_record?
      = image_tag bulletin.image, class: 'img-thumbnail col-2'
    = f.input :image, as: :file, class: 'form-control-file file required form-control'

  p
  .form-actions
    - if f.object.new_record?
      = f.button :submit, t('.create'), class: 'btn btn-primary'
    - else
      = f.button :submit, t('.save'), class: 'btn btn-primary'

app/views/web/bulletins/admin.html.slim
h2
  = t('.bulletins')
p
table.table.table-striped.table-borderless
  thead
    tr
      th.text-bold = t('.name')
      th.text-bold = t('.state')
      th.text-bold = t('.create_at')
      th.text-bold = t('.actions')
  tbody
    - @bulletins.each do |bulletin|
      tr
        td = bulletin.title
        td = t(bulletin.state)
        td = time_ago_in_words(bulletin.created_at)
        td
          = link_to t('.show'), bulletin_path(bulletin), class: 'me-2'
          - if bulletin.may_publish?
            = link_to t('.publish'), publish_bulletin_path(bulletin), data: { turbo_method: :patch }, class: 'me-2'
          - if bulletin.may_reject?
            = link_to t('.reject'), reject_bulletin_path(bulletin), data: { turbo_method: :patch }, class: 'me-2 text-danger'
          - if bulletin.may_archive?
            = link_to t('.archive'), archive_bulletin_path(bulletin), data: { turbo_method: :patch }, class: 'me-2 text-danger'

app/views/web/bulletins/edit.html.slim
h2
  = t('.title')
hr
== render 'form', bulletin: @bulletin

app/views/web/bulletins/index.html.slim
.p-3.p-lg-5.pt-lg-0
  .mb-4
  h2
    = t('.title')
  hr
  .p-3
    = search_form_for @search do |f|
        .row.my-2
          .col-5
            = f.search_field :title_cont, class: 'form-control'
            .form-text.text-muted = t('.search_by_name_hint')
          .col-4
            = f.select :category_id_in, options_from_collection_for_select(Category.all, 'id', 'name'), { include_blank: t('.all_categories') }, class: 'form-select'
            .form-text.text-muted = t('.search_by_category_hint')
          .col-3
            = f.submit t('.search'), class: 'btn btn-primary me-2'
            = link_to t('.reset_search'), url_for, class: 'btn btn-outline-primary'
  #bulletins
  .row.mt-2
    - @bulletins.each do |bulletin|
      == render 'bulletin', bulletin: bulletin
  p
  = paginate @bulletins

app/views/web/bulletins/new.html.slim
h2
  = t('.title')
hr
== render 'form', bulletin: @bulletin

app/views/web/bulletins/profile.html.slim
h2
  = t('.title')
hr
= link_to t('.create'), new_bulletin_path, class: 'me-2'
.p-3
    = search_form_for @search, url: profile_path do |f|
      .row.my-2
        .col-5
          = f.search_field :title_cont, class: 'form-control'
          .form-text.text-muted = t('.search_by_name_hint')
        .col-4
          = f.select :state_in, Bulletin.aasm.states.map { |s| [t(".#{s.name}"), s.name] }, { include_blank: t('.all_states') }, class: 'form-select'
          .form-text.text-muted = t('.search_by_state_hint')
        .col-3
          = f.submit t('.search'), class: 'btn btn-primary me-2'
          = link_to t('.reset_search'), url_for, class: 'btn btn-outline-primary'
.row.mt-2
  table.table.table-borderless
    thead
      tr
        th = t('.name')
        th = t('.state')
        th = t('.create_at')
        th = t('.actions')
    tbody
      - @user_bulletins.each do |bulletin|
        tr
          td = bulletin.title
          td = t(bulletin.state, scope: 'activerecord.attributes.bulletin.state')
          td = time_ago_in_words(bulletin.created_at)
          td
            = link_to t('.show'), bulletin_path(bulletin), class: 'me-2'
            = link_to t('.edit'), edit_bulletin_path(bulletin), class: 'me-2'
            - if bulletin.may_to_moderate?
              = link_to t('.to_moderate'), to_moderate_bulletin_path(bulletin), data: { turbo_method: :patch }, class: 'me-2'
            - if bulletin.may_archive?
              = link_to t('.archive'), archive_bulletin_path(bulletin), data: { turbo_method: :patch, turbo_confirm: t('are_you_sure') }, class: 'me-2 text-danger'
  = paginate @user_bulletins

app/views/web/bulletins/show.html.slim
.card.mb-3
  .card-body
    h4
      =< @bulletin.title
    p
    .col-8
      .col-6
      - if @bulletin.image_attachment
        = image_tag(@bulletin.image, class: 'img-thumbnail mb-2')
      p
        =< @bulletin.description
      .d-flex.justify-content-between.small.text-muted.align-items-end
        .col-4
          span.me-2
            = @bulletin.user.name

app/views/web/bulletins/user_profile.html.slim
h2
  = t('.title')
hr
= link_to t('.create'), new_bulletin_path, class: 'me-2'
.p-3
    = search_form_for @search, url: user_profile_path do |f|
      .row.my-2
        .col-5
          = f.search_field :title_cont, class: 'form-control'
          .form-text.text-muted = t('.search_by_name_hint')
        .col-4
          = f.select :state_in, Bulletin.aasm.states.map { |s| [t(".#{s.name}"), s.name] }, { include_blank: t('.all_states') }, class: 'form-select'
          .form-text.text-muted = t('.search_by_state_hint')
        .col-3
          = f.submit t('.search'), class: 'btn btn-primary me-2'
          = link_to t('.reset_search'), url_for, class: 'btn btn-outline-primary'
.row.mt-2
  table.table.table-borderless
    thead
      tr
        th = t('.name')
        th = t('.state')
        th = t('.create_at')
        th = t('.actions')
    tbody
      - @user_bulletins.each do |bulletin|
        tr
          td = bulletin.title
          td = t(bulletin.state, scope: 'activerecord.attributes.bulletin.state')
          td = time_ago_in_words(bulletin.created_at)
          td
            = link_to t('.show'), bulletin_path(bulletin), class: 'me-2'
            = link_to t('.edit'), edit_bulletin_path(bulletin), class: 'me-2'
            - if bulletin.may_to_moderate?
              = link_to t('.to_moderate'), to_moderate_bulletin_path(bulletin), data: { turbo_method: :patch }, class: 'me-2'
            - if bulletin.may_archive?
              = link_to t('.archive'), archive_bulletin_path(bulletin), data: { turbo_method: :patch, turbo_confirm: t('are_you_sure') }, class: 'me-2 text-danger'
  = paginate @user_bulletins